### PR TITLE
Fix golint errors

### LINKED ISSUE #78: Fix golint error
At the moment `golint` reports a lot of errors. Most of them cover naming conventions and missing documentation.

### PR DESCRIPTION
**Pull request by Hanzei**
The PR fixes all current golint errors. It renames a lot of structs and methods and adds documentation for all public methods and structs. It also moves all tests to a poll_test package to make sure to just test the public API.

Fixes #78

### CODE REVIEW

File: poll/poll_request.go [hunk 1]
```diff
@@ -6,31 +6,36 @@ import (
...
+	ChannelID string
 	Token     string
 	Message   string
 	Emojis    []string
 }
 
 const (
-	backTick             = "`"
+	backTick = "`"
+	//ErrorTextWrongFormat is an error message and is used, if the the message isn`t formated correct
```
Comment (kaakaa) [inline poll/poll_request.go]: typo `the the`

Comment (Hanzei) [reply poll/poll_request.go]: Fixed
